// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClv3sSHdtf4li3Z9AzbnYRR7NrmLqcAMc',
    appId: '1:216577748131:web:9500afbf4e83642a686316',
    messagingSenderId: '216577748131',
    projectId: 'chat-app-68c09',
    authDomain: 'chat-app-68c09.firebaseapp.com',
    storageBucket: 'chat-app-68c09.appspot.com',
    measurementId: 'G-46J0588F94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgquo9d-xS6WMh9VpOXHfoMocCg_QnNZM',
    appId: '1:216577748131:android:158d0e87eef8d1b5686316',
    messagingSenderId: '216577748131',
    projectId: 'chat-app-68c09',
    storageBucket: 'chat-app-68c09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoh0MVuc-Nyb6r1blnY0KQC3VB1H0nCok',
    appId: '1:216577748131:ios:bbdd8e36d251c36c686316',
    messagingSenderId: '216577748131',
    projectId: 'chat-app-68c09',
    storageBucket: 'chat-app-68c09.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoh0MVuc-Nyb6r1blnY0KQC3VB1H0nCok',
    appId: '1:216577748131:ios:dd6a0c74fbb69b4a686316',
    messagingSenderId: '216577748131',
    projectId: 'chat-app-68c09',
    storageBucket: 'chat-app-68c09.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClv3sSHdtf4li3Z9AzbnYRR7NrmLqcAMc',
    appId: '1:216577748131:web:a40d3d67bc3a5389686316',
    messagingSenderId: '216577748131',
    projectId: 'chat-app-68c09',
    authDomain: 'chat-app-68c09.firebaseapp.com',
    storageBucket: 'chat-app-68c09.appspot.com',
    measurementId: 'G-CY4FT2WSNS',
  );
}
